### ISSUE TITLE
Create new *blockMeshDict*

### ISSUE THREAD

**Issue by AndreWeiner** [FabianGabriel/Active_flow_control_past_cylinder_using_DRL#2]
Hi Fabian,
as a warm-up, I would like to create an alternative mesh for the cylinder flow setup. The current setup uses a combination of the native OpenFOAM meshers *blockMesh* and *snappyHexMesh*. To simplify and accelerate the mesh creation, I would like to create the mesh entirely in *blockMesh*. I suggest the following steps

- get familiar with the current simulation setup
- check out the [OpenFOAM user guide](https://www.openfoam.com/documentation/user-guide/4-mesh-generation-and-conversion/4.3-mesh-generation-with-the-blockmesh-utility) of *blockMesh*
- [this tutorial](https://www.openfoam.com/documentation/tutorial-guide/2-incompressible-flow/2.2-flow-around-a-cylinder#x7-390002.2) from the tutorial guide might be helpful
- modify this existing *blockMeshDict* and remove *snappyHexMeshDict* and *extrudeMeshDict*

![blocking_sketch](https://user-images.githubusercontent.com/8482575/116690148-4533d200-a9b9-11eb-8d65-07797b4f23b8.png)

If questions come up, you can post them in this issue.

Best, Andre

**Comment by FabianGabriel** [comment]
Hi Andre,
I have a little problem understanding this task. 
Namely: What kind of mesh should be created here? Just the relatively simple mesh that you have attached as an image? Or should these larger blocks themselves also be divided?
Best Regards
 Fabian

**Comment by FabianGabriel** [comment]
Hi Andre,
I just did this task with the commit: 2aea2b4fcb5062486391c8306517fb03c2bf80f5
Let me know if I can improve on certain aspects on this mesh.

Best, Fabian

**Comment by AndreWeiner** [comment]
Hi Fabian,

the mesh looks pretty good. There is one point for improvement. Unfortunately, I pointed you to a tutorial that uses the old `#calc` syntax. The old preprocessing requires runtime compilation each time the mesh is created, as you probably noticed. The new `#eval` works much quicker. Here are some links that will help you to replace the old preprocessing with the new one:
- example [blockMeshDict](https://github.com/AndreWeiner/sgs_model_test_transient/blob/master/openfoam/test_cases/blockMesh_ref_0/system/blockMeshDict)
- overview of data types and functions in the official [documentation](https://www.openfoam.com/documentation/guides/latest/doc/openfoam-guide-expression-syntax.html)

Best, Andre

**Comment by FabianGabriel** [comment]
Hi Andre,

I have now replaced every `#calc` with `#eval` statements in commit 1d8e52dd1e86b36d97b21ef8fb7d28e2e83142b3

Best, Fabian
